from . import unit_model
from . import stock
from . import product_template
from . import purchase_order
from . import purchase_requisition
from . import sale_order
from . import rental_order
from . import repair_order
from . import crm_lead
from . import res_partner
from . import res_company
from . import res_employee
from . import product_unit
