from . import unit_model
from . import product_category
from . import account_account
from . import account_move
from . import account_payment
from . import stock
from . import product_template
from . import product_pricelist
from . import purchase_order
from . import purchase_requisition
from . import sale_order
from . import rental_order
from . import sale_subscription
from . import repair_order
from . import crm_lead
from . import res_partner
from . import res_company
from . import res_employee
from . import product_unit
